### ISSUE TITLE
npm install after a fresh clone causes warnings

### ISSUE THREAD

**Issue by maboa** [mdn/interactive-examples#323]
This could just be me :) so if somebody could verify, that would be great. Note these warnings/errors don't appear to prevent the Interactive Editor running.

Here's what I get : 
```
MarkB$ npm install
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-D5JUjPyJbaJDkuAazpVnSfVkLlpeO3wDlPROTMLGKG1zMFNFRgrciKo1ltz/AzNTkqE0HzDx655QOL51N06how== integrity checksum failed when using sha512: wanted sha512-D5JUjPyJbaJDkuAazpVnSfVkLlpeO3wDlPROTMLGKG1zMFNFRgrciKo1ltz/AzNTkqE0HzDx655QOL51N06how== but got sha1-x6vpzIuHwLqodrGf3oP9RkeX44w=. (4087 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> fsevents@1.1.2 install /Users/MarkB/Projects/interactive-examples/node_modules/chokidar-cli/node_modules/fsevents
> node install

[fsevents] Success: "/Users/MarkB/Projects/interactive-examples/node_modules/chokidar-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.2.tgz install /Users/MarkB/Projects/interactive-examples/node_modules/fsevents
> node install

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/MarkB/Projects/interactive-examples/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:270:33)
node-pre-gyp ERR! stack     at install (/Users/MarkB/Projects/interactive-examples/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:165:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/MarkB/Projects/interactive-examples/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/Users/MarkB/Projects/interactive-examples/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/MarkB/Projects/interactive-examples/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:624:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:635:10)
node-pre-gyp ERR! stack     at Module.load (module.js:545:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:508:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:500:3)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/MarkB/Projects/interactive-examples/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/MarkB/Projects/interactive-examples/node_modules/fsevents
node-pre-gyp ERR! node -v v8.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Cannot read property 'version' of null
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.2.tgz (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.2.tgz install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 983 packages in 23.517s
```

**Comment by schalkneethling** [comment]
@maboa It looks to be related to this: https://github.com/npm/npm/issues/11632

Perhaps try upgrading Nodejs as I see the issue above is closed?

**Comment by schalkneethling** [comment]
@maboa This still happening for you?

* [ ] Yup
* [ ] Nope

**Comment by schalkneethling** [comment]
We have had a bunch of new contributors all starting of with a fresh clone, and so far no reports of this problem. Closing for now. Please feel free to reopen should the problem happen again.
